from flask_wtf import Form
from wtforms import StringField, TextField, BooleanField, validators, PasswordField, Form, IntegerField, DateField, TextAreaField
from wtforms_components import DateRange
from datetime import datetime, date

# Each of these forms is imported into the main app and used for creating 
# fields for writing and editing reports

class RegistrationForm(Form):
		firstname = StringField('First Name', [validators.Length(min=2, max=20)])
		lastname = StringField('Last Name', [validators.Length(min=2, max=20)])
		username = StringField('Username', [validators.Length(min=4, max=20)])
		email = StringField('Email Address', [validators.Email(), validators.Length(min=10, max=50)])
		password = PasswordField('Password', [validators.DataRequired(),
			validators.EqualTo('confirm', message= "Passwords must match.")])
		confirm = PasswordField('Repeat Password')
		
class AddressForm(Form):
		Requester = StringField('Customer Name', [validators.Length(min=2, max=40)])
		StreetAddress = StringField('Street Address', [validators.Length(min=5,max=50)])
		City = StringField('City', [validators.Length(min=4, max=20)])
		State = StringField('State', [validators.Length(min=2, max=2)])
		ZipCode = StringField('Zip Code', [validators.DataRequired(),validators.Length(min=5,max=5)])
		
class ReportForm(Form):
		RID = IntegerField('Report ID Number', [validators.DataRequired()])
		Date = DateField('Date of Inspection', validators=[DateRange(min=date.today())], render_kw={"placeholder":"YYYY-MM-DD"})
		UID = IntegerField('User ID', [validators.DataRequired()])

class RoofAtticForm(Form):
		RoofCoverings = TextAreaField('Roof Coverings', [validators.Length(min=2, max=255)])
		RCInsp = BooleanField('Inspected/ Not Inspected')
		Flashings = TextAreaField('Flashings', [validators.Length(min=2, max=255)])
		FlasInsp = BooleanField('Inspected/ Not Inspected')
		SkylightChimney = TextAreaField('Skylight and Chimney', [validators.Length(min=2, max=255)])
		SkChInsp = BooleanField('Inspected/ Not Inspected')
		aVentilation = TextAreaField('Ventilation', [validators.Length(min=2, max=255)])
		aVentInsp = BooleanField('Inspected/ Not Inspected')
		aDrainage = TextAreaField('Drainage', [validators.Length(min=2, max=255)])
		aDraiInsp = BooleanField('Inspected/ Not Inspected')
		StructureAttic = TextAreaField('Attic Structure', [validators.Length(min=2, max=255)])
		StAtInsp = BooleanField('Inspected/ Not Inspected')
		FansThermostat = TextAreaField('Fans and Thermostat', [validators.Length(min=2, max=255)])
		FaThInsp = BooleanField('Inspected/ Not Inspected')
		aInsulation = TextAreaField('Insulation', [validators.Length(min=2, max=255)])
		aInsuInsp = BooleanField('Inspected/ Not Inspected')
		VisibleWiring = TextAreaField('Visible Wiring', [validators.Length(min=2, max=255)])
		ViWiInsp = BooleanField('Inspected/ Not Inspected')
		
class ExteriorForm(Form):
		WallFlashTrim = TextAreaField('Walls, Flashings, and Trim', [validators.Length(min=2, max=255)])
		WaFTInsp = BooleanField('Inspected/ Not Inspected')
		exDoors = TextAreaField('Doors', [validators.Length(min=2, max=255)])
		exDoorInsp = BooleanField('Inspected/ Not Inspected')
		exWindows = TextAreaField('Windows', [validators.Length(min=2, max=255)])
		exWindInsp = BooleanField('Inspected/ Not Inspected')
		DeckBalcSteps = TextAreaField('Decks, Balconies, and Steps', [validators.Length(min=2, max=255)])
		DeBSInsp = BooleanField('Inspected/ Not Inspected')
		VegetDrainDriveWalk = TextAreaField('Vegetation, Drains, Drive- and Walkways', [validators.Length(min=2, max=255)])
		VDDWInsp = BooleanField('Inspected/ Not Inspected')
		EavesFascia = TextAreaField('Eaves and Fascia', [validators.Length(min=2, max=255)])
		EaFaInsp = BooleanField('Inspected/ Not Inspected')
		exPlumbing = TextAreaField('Plumbing', [validators.Length(min=2, max=255)])
		exPlumInsp = BooleanField('Inspected/ Not Inspected')
		Outlets = TextAreaField('Outlets', [validators.Length(min=2, max=255)])
		OutlInsp = BooleanField('Inspected/ Not Inspected')
		
class GarageForm(Form):
		gCeiling = TextAreaField('Garage Ceiling', [validators.Length(min=2, max=255)])
		gCeilInsp = BooleanField('Inspected/ Not Inspected')
		gWalls = TextAreaField('Garage Walls', [validators.Length(min=2, max=255)])
		gWallInsp = BooleanField('Inspected/ Not Inspected')
		gFloor = TextAreaField('Garage Floor', [validators.Length(min=2, max=255)])
		gFlooInsp = BooleanField('Inspected/ Not Inspected')
		gDoor = TextAreaField('Garage Door', [validators.Length(min=2, max=255)])
		gDoorInsp = BooleanField('Inspected/ Not Inspected')
		InnerDoor = TextAreaField('Door from Garage to House', [validators.Length(min=2, max=255)])
		InDoInsp = BooleanField('Inspected/ Not Inspected')
		GDOperator = TextAreaField('Garage Door Operators', [validators.Length(min=2, max=255)])
		GDOpInsp = BooleanField('Inspected/ Not Inspected')
		
class KitchenForm(Form):
		kCeiling = TextAreaField('Ceiling', [validators.Length(min=2, max=255)])
		kCeilInsp = BooleanField('Inspected/ Not Inspected')
		kWalls = TextAreaField('Walls', [validators.Length(min=2, max=255)])
		kWallInsp = BooleanField('Inspected/ Not Inspected')
		kFloor = TextAreaField('Floor', [validators.Length(min=2, max=255)])
		kFlooInsp = BooleanField('Inspected/ Not Inspected')
		PantryDoor = TextAreaField('Pantry Doors', [validators.Length(min=2, max=255)])
		PaDoInsp = BooleanField('Inspected/ Not Inspected')
		kWindows = TextAreaField('Windows', [validators.Length(min=2, max=255)])
		kWindInsp = BooleanField('Inspected/ Not Inspected')
		kCountersCabinets = TextAreaField('Counters and Cabinets', [validators.Length(min=2, max=255)])
		kCoCaInsp = BooleanField('Inspected/ Not Inspected')
		kPlumbing = TextAreaField('Plumbing, Drains & Water Supply', [validators.Length(min=2, max=255)])
		kPlumInsp = BooleanField('Inspected/ Not Inspected')
		kOutletSwitchFix = TextAreaField('Outlets, Switches, & Fixtures', [validators.Length(min=2, max=255)])
		kOuSFInsp = BooleanField('Inspected/ Not Inspected')
		Dishwash = TextAreaField('Dishwasher', [validators.Length(min=2, max=255)])
		DishInsp = BooleanField('Inspected/ Not Inspected')
		RangeOven = TextAreaField('Range & Oven', [validators.Length(min=2, max=255)])
		RaOvInsp = BooleanField('Inspected/ Not Inspected')
		Microwave = TextAreaField('Microwave', [validators.Length(min=2, max=255)])
		MicrInsp = BooleanField('Inspected/ Not Inspected')
		
class RoomsForm(Form):
		rCeiling = TextAreaField('Ceiling', [validators.Length(min=2, max=255)])
		rCeilInsp = BooleanField('Inspected/ Not Inspected')
		rWalls = TextAreaField('Walls', [validators.Length(min=2, max=255)])
		rWallInsp = BooleanField('Inspected/ Not Inspected')
		rFloor = TextAreaField('Floor', [validators.Length(min=2, max=255)])
		rFlooInsp = BooleanField('Inspected/ Not Inspected')
		StairRailBalc = TextAreaField('Stairs, Balconies, & Railings', [validators.Length(min=2, max=255)])
		SRBaInsp = BooleanField('Inspected/ Not Inspected')
		rDoor = TextAreaField('Doors', [validators.Length(min=2, max=255)])
		rDoorInsp = BooleanField('Inspected/ Not Inspected')
		rWindows = TextAreaField('Windows', [validators.Length(min=2, max=255)])
		rWindInsp = BooleanField('Inspected/ Not Inspected')
		rOutletSwitchFix = TextAreaField('Outlets, Switches & Fixtures', [validators.Length(min=2, max=255)])
		rOuSFInsp = BooleanField('Inspected/ Not Inspected')
		
class BathroomsForm(Form):
		CounterCabinet = TextAreaField('Counters & Cabinets', [validators.Length(min=2, max=255)])
		bCoCaInsp = BooleanField('Inspected/ Not Inspected')
		bDoor = TextAreaField('Doors', [validators.Length(min=2, max=255)])
		bDoorInsp = BooleanField('Inspected/ Not Inspected')
		bWindows = TextAreaField('Windows', [validators.Length(min=2, max=255)])
		bWindInsp = BooleanField('Inspected/ Not Inspected')
		bPlumbing = TextAreaField('Plumbing', [validators.Length(min=2, max=255)])
		bPlumInsp = BooleanField('Inspected/ Not Inspected')
		bOutletSwitchFix = TextAreaField('Outlets, Switches, & Fixtures', [validators.Length(min=2, max=255)])
		bOuSFInsp = BooleanField('Inspected/ Not Inspected')
		ExhaustFan = TextAreaField('Exhaust Fan', [validators.Length(min=2, max=255)])
		ExFaInsp = BooleanField('Inspected/ Not Inspected')

class StructureForm(Form):
		FoundBasement = TextAreaField('Foundation, Basement, & Crawlspaces', [validators.Length(min=2, max=255)])
		FoBaInsp = BooleanField('Inspected/ Not Inspected')
		sWalls = TextAreaField('Walls', [validators.Length(min=2, max=255)])
		sWallInsp = BooleanField('Inspected/ Not Inspected')
		Columns = TextAreaField('Columns', [validators.Length(min=2, max=255)])
		ColuInsp = BooleanField('Inspected/ Not Inspected')
		sFloors = TextAreaField('Floors', [validators.Length(min=2, max=255)])
		sFlooInsp = BooleanField('Inspected/ Not Inspected')
		sCeiling = TextAreaField('Ceiling', [validators.Length(min=2, max=255)])
		sCeilInsp = BooleanField('Inspected/ Not Inspected')
		sInsulation = TextAreaField('Insulation', [validators.Length(min=2, max=255)])
		sInsuInsp = BooleanField('Inspected/ Not Inspected')
		VaporRetarders = TextAreaField('Vapor Retarders', [validators.Length(min=2, max=255)])
		VaReInsp = BooleanField('Inspected/ Not Inspected')
		sVentilation = TextAreaField('Ventilation of Area', [validators.Length(min=2, max=255)])
		sVentInsp = BooleanField('Inspected/ Not Inspected')
		
class PlumbingForm(Form):
		DrainWasteVent = TextAreaField('Plumbing Drain, Waste, & Vent Systems', [validators.Length(min=2, max=255)])
		DrWVInsp = BooleanField('Inspected/ Not Inspected')
		H2OSupplyDist = TextAreaField('Water Supply & Distribution', [validators.Length(min=2, max=255)])
		HSDiInsp = BooleanField('Inspected/ Not Inspected')
		HotWaterSupply = TextAreaField('Hot Water Systems', [validators.Length(min=2, max=255)])
		HWSuInsp = BooleanField('Inspected/ Not Inspected')
		MainShut = TextAreaField('Main Water Shutoff', [validators.Length(min=2, max=255)])
		MaShInsp = BooleanField('Inspected/ Not Inspected')
		FuelStorDist = TextAreaField('Fuel Storage & Distribution', [validators.Length(min=2, max=255)])
		FSDiInsp = BooleanField('Inspected/ Not Inspected')
		FuelShut = TextAreaField('Main Fuel Shutoff', [validators.Length(min=2, max=255)])
		FuShInsp = BooleanField('Inspected/ Not Inspected')
		
class ElectricalForm(Form):
		EntrConductor = TextAreaField('Service Entrance Conductors', [validators.Length(min=2, max=255)])
		EnCoInsp = BooleanField('Inspected/ Not Inspected')
		ServGroundOverMainPanel = TextAreaField('Service/Grounding Equipment, Main OverCurrent Device, Main & Dist. Panels', [validators.Length(min=2, max=255)])
		SGOPInsp = BooleanField('Inspected/ Not Inspected')
		BranchEquip = TextAreaField('Branch Circuit Equipment', [validators.Length(min=2, max=255)])
		BrEqInsp = BooleanField('Inspected/ Not Inspected')
		DevFix = TextAreaField('Devices & Fixtures', [validators.Length(min=2, max=255)])
		DeFiInsp = BooleanField('Inspected/ Not Inspected')
		PolarityGround = TextAreaField('Polarity & Grounding Receptacles', [validators.Length(min=2, max=255)])
		PoGrInsp = BooleanField('Inspected/ Not Inspected')
		OpGFCI = TextAreaField('Operation of GFCI', [validators.Length(min=2, max=255)])
		GFCIInsp = BooleanField('Inspected/ Not Inspected')
		SmokeDetect = TextAreaField('Smoke Detectors', [validators.Length(min=2, max=255)])
		SmDeInsp = BooleanField('Inspected/ Not Inspected')
		CarbMonDet = TextAreaField('Carbon Monoxide Detectors', [validators.Length(min=2, max=255)])
		CaMoInsp = BooleanField('Inspected/ Not Inspected')
		LocatMainDistPan = TextAreaField('Location of Main & Distribution Panels', [validators.Length(min=2, max=255)])
		LMDPInsp = BooleanField('Inspected/ Not Inspected')
		
class HeatCentAirForm(Form):
		HeatEquip = TextAreaField('Heating Equipment', [validators.Length(min=2, max=255)])
		HeEqInsp = BooleanField('Inspected/ Not Inspected')
		NormOpCont = TextAreaField('Normal Operating Controls', [validators.Length(min=2, max=255)])
		NOCoInsp = BooleanField('Inspected/ Not Inspected')
		AutoSafeCont = TextAreaField('Automatic Safety Controls', [validators.Length(min=2, max=255)])
		ASCoInsp = BooleanField('Inspected/ Not Inspected')
		DistSys = TextAreaField('Distribution Systems', [validators.Length(min=2, max=255)])
		DiSyInsp = BooleanField('Inspected/ Not Inspected')
		ChimneyFlueVent = TextAreaField('Chimneys, Flues, & Vents', [validators.Length(min=2, max=255)])
		CFVeInsp = BooleanField('Inspected/ Not Inspected')
		SolidFuelHeatDev = TextAreaField('Solid Fuel Heating Devices', [validators.Length(min=2, max=255)])
		SFHDInsp = BooleanField('Inspected/ Not Inspected')
		CoolAirHandEq = TextAreaField('Cooling & Air Handler Equipment', [validators.Length(min=2, max=255)])
		CAHEInsp = BooleanField('Inspected/ Not Inspected')
		NormOpEq = TextAreaField('Normal Operating Equipment', [validators.Length(min=2, max=255)])
		NOEqInsp = BooleanField('Inspected/ Not Inspected')

